### PR TITLE
Cid info fix + sorting storage jobs

### LINKED ISSUE #722: pow storage-jobs executing is inconsistent
The order of the resulting storageJobs are inconsistent. It would be helpful to have some sort of order so it's easy to compare changes and see progress.

### PR DESCRIPTION
**Pull request by asutula**
There was a bug where the `Data.Info()` method was usually only returning one result. Fixed here.

Also adds sorting by cid to the results of `Data.Info()` and makes sure all storage job list responses are sorted by date.

closes #722

### CODE REVIEW

File: api/server/user/data.go [hunk 1]
```diff
@@ -224,6 +225,9 @@ func (s *Service) CidInfo(ctx context.Context, req *userPb.CidInfoRequest) (*use
 		}
 		res = append(res, cidInfo)
 	}
+	sort.Slice(res, func(a, b int) bool {
+		return res[a].Cid < res[b].Cid
```
Comment (asutula) [inline api/server/user/data.go:229]: Just sorting by cid so the results are in a consistent order. There's nothing better to sort by really.

File: ffs/api/istore.go [hunk 2]
```diff
@@ -126,9 +128,9 @@ func (s *instanceStore) getStorageConfigs(cids ...cid.Cid) (map[cid.Cid]ffs.Stor
 			if err != nil {
 				return nil, fmt.Errorf("decoding cid: %s", err)
 			}
-			if len(rawRes) > 0 {
+			if len(filter) > 0 {
 				// we have a filter, check it
-				if _, ok := rawRes[c]; ok {
+				if _, ok := filter[c]; ok {
```
Comment (asutula) [inline ffs/api/istore.go:133]: This was just a stupid mistake.

File: ffs/scheduler/internal/sjstore/sjstore.go [hunk 3]
```diff
@@ -457,6 +457,11 @@ func mappedJobs(m map[ffs.APIID]map[cid.Cid]*ffs.StorageJob, iid ffs.APIID, cids
 			}
 		}
 	}
+
+	sort.Slice(res, func(a, b int) bool {
+		return res[a].CreatedAt < res[b].CreatedAt
+	})
```
Comment (asutula) [inline ffs/scheduler/internal/sjstore/sjstore.go:463]: Makes sure storage job results are always sorted ascending by time.

**Review by jsign — APPROVED** [review]
LGTM
