### PR TITLE
index: new fault index, include new info in miners index

### LINKED ISSUE #235: index/slashing: fix strategy for new version
The current way of building the slashing index doesn't work anymore due to changes in the internals of Lotus VM. There are confirmed ideas to accommodate, but still in the process of deciding the right time since changes are still happening in the _faults_ logic of the VM.

### PR DESCRIPTION
**Pull request by jsign**
This PR:
- Re-implements the slashing index, which is now called _Fault index_ to be more precise. It records at which epochs miners have failed to provide proof of sectors. (Close #235)
- Include _Sector Size_ as new data in the miner index, since it sounds interesting to consider when selecting miners. If your data fits in a smaller sector than 32Gib, you might store it faster if you choose the right miner. (See #393)
- Include the _Active Deals_ count of miners in the index, which a higher number indicates the miner is storing more data and can possibly infer "more people might" be relying on him.
- `pow ffs logs` also returns history by default, so to get a clearer view of things.
- Fix setup of production docker-compose to connect Lotus to IPFS. Tested in prod when making deals with Powergate with miner `t01608`.

Changes already published in cloud: [Dashboard](http://35.238.61.140:3000/d/p4TiQMYWk/textile-filecoin?orgId=1&refresh=5s&from=now-30m&to=now), [Miner index](http://35.238.61.140:8889/index/miners), [Ask index](http://35.238.61.140:8889/index/ask), [Fault index](http://35.238.61.140:8889/index/faults)

### CODE REVIEW

File: index/faults/faults.go [hunk 1]
```diff
@@ -119,163 +118,120 @@ func (s *Index) Close() error {
...
 			j = len(path)
 		}
-		if err := updateFromPath(s.ctx, s.api, &index, path[i:j]); err != nil {
-			return fmt.Errorf("getting update from path section: %s", err)
+
+		// Get section head and length, and get all faults happened
+		// in this section and include it into the updating index.
+		sectionLength := abi.ChainEpoch(j - i)
+		sectionHeadTs := path[j-1].Key()
+		faults, err := s.api.StateAllMinerFaults(s.ctx, sectionLength, sectionHeadTs)
```
Comment (jsign) [inline index/faults/faults.go:191]: So this is the new API we're leveraging to get miners faults.
We abandoned a more complex strategy getting internal miner state and inspecting fields.

File: index/faults/faults.go [hunk 2]
```diff
@@ -119,163 +118,120 @@ func (s *Index) Close() error {
...
-			if !ok {
-				log.Debugf("casting slashedAt %v from %s at %d failed", iSlashedAt, addr, pts.Height)
-				return
-			}
-			slashedAt := uint64(fSlashedAt)
-			if slashedAt != 0 {
-				lock.Lock()
-				ret[addr] = (slashedAt)
-				lock.Unlock()
-			}
```
Comment (jsign) [inline index/faults/faults.go]: Good that went away.

File: index/miner/onchain.go [hunk 3]
```diff
@@ -159,16 +160,33 @@ func updateForAddrs(ctx context.Context, api *apistruct.FullNodeStruct, chainInd
...
+
+	// Active deals
+	sectors, err := c.StateMinerSectors(ctx, addr, nil, false, types.EmptyTSK)
+	if err != nil {
+		return OnChainData{}, fmt.Errorf("getting sectors: %s", err)
+	}
+	var activeDeals uint64
+	for _, s := range sectors {
+		activeDeals += uint64(len(s.Info.Info.DealIDs))
+	}
```
Comment (jsign) [inline index/miner/onchain.go:185]: New data added to the miners index.

File: index/miner/types.go [hunk 4]
```diff
@@ -6,20 +6,21 @@ import (
...
+	Meta    MetaIndex
+	OnChain ChainIndex
 }
 
 // ChainIndex contains on-chain information about miners
 type ChainIndex struct {
 	LastUpdated int64
-	Power       map[string]Power
+	Miners      map[string]OnChainData
 }
```
Comment (jsign) [inline index/miner/types.go:17]: So here is a change in structure of the index data. 
Instead of having data _per-dimension_ ("Power", "SectorSize", "ActiveDeals"), sounds much more useful to group the data by miner. Seems more natural. Unfortunately, that change scattered to many files but sounds like worth it.

File: index/miner/types.go [hunk 5]
```diff
@@ -6,20 +6,21 @@ import (
...
-// Power contains power information of a miner
-type Power struct {
-	Power    uint64
-	Relative float64
+type OnChainData struct {
+	Power         uint64
+	RelativePower float64
+	SectorSize    uint64
+	ActiveDeals   uint64
 }
```
Comment (jsign) [inline index/miner/types.go:25]: If adding more info in the index, would mean adding more fields here.

File: api/stub/faults.go [hunk 6]
```diff
@@ -0,0 +1,30 @@
+package stub
```
Comment (asutula) [inline api/stub/faults.go:1]: We can probably get rid of all this stub code now that we have a reliable Devnet setup. No big deal either way I guess.

File: index/faults/faults.go [hunk 7]
```diff
@@ -0,0 +1,244 @@
...
+	defer close(s.finished)
+	if err := s.updateIndex(); err != nil {
+		log.Errorf("initial updating faults index: %s", err)
+	}
+	for {
+		select {
+		case <-s.ctx.Done():
+			log.Info("graceful shutdown of background faults updater")
+			return
+		case <-time.After(util.AvgBlockTime):
```
Comment (asutula) [inline index/faults/faults.go:132]: Ah cool, so you are basically polling every `AvgBlockTime`? No listening for chain updates etc

File: index/miner/types.go (hunk 4 above)
Comment (asutula) [reply index/miner/types.go:17]: Yea good call, much better for consuming this way. Give you the total miner view in a simple way then it's easy to map to lists of single types.

**Comment by jsign** [comment]
Closes #421
